const actionLabels: Record<string, string> = {
  ACT_CREATED: 'Создан акт',
  ACT_UPDATED: 'Изменён акт',
  ACT_DELETED: 'Удалён акт',
  ACT_PERMANENTLY_DELETED: 'Акт удалён навсегда',
  ACT_SIGNED_PARTY1: 'IT подписал акт',
  ACT_SIGNED_PARTY2: 'Получатель подписал акт',
  ISSUE_RECIPIENT_SIGNED: 'Получатель подписал акт',
  ISSUE_COMPLETED: 'Выдача завершена',
  RETURN_STARTED: 'Начат возврат',
  RETURN_MANAGER_SIGNED: 'IT подтвердил возврат',
  RETURN_COMPLETED: 'Возврат завершён',
  IPAD_ACT_CREATED: 'Создан iPad-акт',
  IPAD_APPENDIX_CREATED: 'Создано приложение к iPad-акту',
  IPAD_APPENDIX_APPLIED: 'Применено приложение к iPad-акту',
  IPAD_APPENDIX_CANCELLED: 'Отменено приложение к iPad-акту',
  IPAD_APPENDIX_RESPONSIBLE_SIGNED: 'Ответственный подписал приложение',
  IPAD_APPENDIX_ISSUER_SIGNED: 'IT подписал приложение',
  IPAD_YEAR_END_RETURN_COMPLETED: 'Годовой возврат iPad завершён',
  IPAD_DEVICE_CREATED: 'Добавлен iPad',
  IPAD_DEVICE_UPDATED: 'Изменён iPad',
  IPAD_DEVICE_DELETED: 'Удалён iPad',
  IPAD_REPAIR_COMPLETED: 'Завершён ремонт iPad',
  DEVICE_CREATED: 'Добавлена техника',
  DEVICE_UPDATED: 'Изменена техника',
  DEVICE_DELETED: 'Удалена техника',
  SMALL_EQUIPMENT_CREATED: 'Добавлена мелкая техника',
  SMALL_EQUIPMENT_DELETED: 'Удалена мелкая техника',
  CATEGORY_CREATED: 'Создана категория техники',
  CATEGORY_UPDATED: 'Изменена категория техники',
  CATEGORY_DELETED: 'Удалена категория техники',
  PARTICIPANT_CREATED: 'Добавлен участник',
  PARTICIPANT_UPDATED: 'Изменён участник',
  PARTICIPANT_DEACTIVATED: 'Участник деактивирован',
  KIOSK_ENROLLMENT_CREATED: 'Создан код привязки планшета',
  KIOSK_ENROLLED: 'Планшет привязан',
  KIOSK_REVOKED: 'Планшет отозван',
  MANUAL_FINAL_EMAIL_ENQUEUED: 'Финальный документ поставлен в очередь',
  MANUAL_FINAL_EMAIL_QUEUED: 'Финальный документ поставлен в очередь',
  EMAIL_ENQUEUED: 'Письмо поставлено в очередь',
  REMINDER_SENT: 'Отправлено напоминание',
};

export const auditEntityLabels: Record<string, string> = {
  ACT: 'Акт',
  TEMPLATE: 'Шаблон',
  PARTICIPANT: 'Участник',
  INVENTORY: 'Техника',
  INVENTORY_DEVICE: 'Техника',
  INVENTORY_CATEGORY: 'Категория техники',
  SMALL_EQUIPMENT: 'Мелкая техника',
  IPAD_DEVICE: 'iPad',
  IPAD_APPENDIX: 'Приложение iPad',
  KIOSK: 'Планшет',
  USER: 'Пользователь',
};

export const auditActionLabel = (action: string) => actionLabels[action] || action.replace(/_/g, ' ').toLowerCase();
export const auditEntityLabel = (entity: string) => auditEntityLabels[entity] || entity;
